/*
 week 3.1 -

1)introduction
2) MONGO DB
3) POSTGRES INSTALLATION
4) MIDDLEWARE AND GLOBAL CATCHES
5) Res.send() and res.join()
6) MIDDLEWARE AND REQUEST BODY
7) 3 WAYS OF SENDING INPUT TO RESPONSE
8) INPUT VALIDATION


*/